/** Preset theme definitions */

import { BuddyTheme } from './derive'

export const PRESET_THEMES: BuddyTheme[] = [
  // ===== Dark themes (15) =====
  {
    id: 'buddy-dark',
    name: 'Buddy Dark',
    type: 'dark',
    surface: '#18181a',
    ink: '#e8e8e3',
    accent: '#339cff',
    success: '#40c977',
    danger: '#fa423e',
    contrast: 60,
  },
  {
    id: 'codex-dark',
    name: 'Codex Dark',
    type: 'dark',
    surface: '#111111',
    ink: '#ffffff',
    accent: '#0169cc',
    success: '#40c977',
    danger: '#fa423e',
    contrast: 60,
  },
  {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    surface: '#282a36',
    ink: '#f8f8f2',
    accent: '#ff79c6',
    success: '#50fa7b',
    danger: '#ff5555',
    contrast: 60,
  },
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    type: 'dark',
    surface: '#1e1e2e',
    ink: '#cdd6f4',
    accent: '#cba6f7',
    success: '#a6e3a1',
    danger: '#f38ba8',
    contrast: 58,
  },
  {
    id: 'catppuccin-macchiato',
    name: 'Catppuccin Macchiato',
    type: 'dark',
    surface: '#181825',
    ink: '#cad3f8',
    accent: '#c7a4f5',
    success: '#a6da95',
    danger: '#ed8796',
    contrast: 58,
  },
  {
    id: 'nord',
    name: 'Nord',
    type: 'dark',
    surface: '#2e3440',
    ink: '#d8dee9',
    accent: '#88c0d0',
    success: '#a3be8c',
    danger: '#bf616a',
    contrast: 55,
  },
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    type: 'dark',
    surface: '#282c34',
    ink: '#abb2bf',
    accent: '#4d78cc',
    success: '#98c379',
    danger: '#e06c75',
    contrast: 60,
  },
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    type: 'dark',
    surface: '#1a1b26',
    ink: '#a9b1d6',
    accent: '#7aa2f7',
    success: '#9ece6a',
    danger: '#f7768e',
    contrast: 58,
  },
  {
    id: 'gruvbox-dark',
    name: 'Gruvbox Dark',
    type: 'dark',
    surface: '#282828',
    ink: '#ebdbb2',
    accent: '#fe8019',
    success: '#b8bb26',
    danger: '#fb4934',
    contrast: 55,
  },
  {
    id: 'kanagawa',
    name: 'Kanagawa Wave',
    type: 'dark',
    surface: '#1f1f28',
    ink: '#dcd7ba',
    accent: '#658594',
    success: '#76956a',
    danger: '#c34043',
    contrast: 55,
  },
  {
    id: 'rose-pine',
    name: 'Rose Pine',
    type: 'dark',
    surface: '#191724',
    ink: '#e0def4',
    accent: '#ebbcba',
    success: '#31748f',
    danger: '#eb6f92',
    contrast: 58,
  },
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    type: 'dark',
    surface: '#0d1117',
    ink: '#e6edf3',
    accent: '#1f6feb',
    success: '#3fb950',
    danger: '#f85149',
    contrast: 50,
  },
  {
    id: 'material-palenight',
    name: 'Material Palenight',
    type: 'dark',
    surface: '#292d3e',
    ink: '#eeffff',
    accent: '#80cbc4',
    success: '#c3e88d',
    danger: '#ff5370',
    contrast: 58,
  },
  {
    id: 'ayu-dark',
    name: 'Ayu Dark',
    type: 'dark',
    surface: '#0b0e14',
    ink: '#bfbdb6',
    accent: '#e6b450',
    success: '#c2d94c',
    danger: '#f07178',
    contrast: 55,
  },
  {
    id: 'vitesse-dark',
    name: 'Vitesse Dark',
    type: 'dark',
    surface: '#121212',
    ink: '#dbd7ca',
    accent: '#4d9375',
    success: '#80a665',
    danger: '#cb7676',
    contrast: 55,
  },

  // ===== Light themes (8) =====
  {
    id: 'buddy-light',
    name: 'Buddy Light',
    type: 'light',
    surface: '#f3f3f1',
    ink: '#1c1c1a',
    accent: '#6b6b66',
    success: '#00a240',
    danger: '#ba2623',
    contrast: 45,
  },
  {
    id: 'codex-light',
    name: 'Codex Light',
    type: 'light',
    surface: '#ffffff',
    ink: '#1a1c1f',
    accent: '#0169cc',
    success: '#00a240',
    danger: '#ba2623',
    contrast: 45,
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    type: 'light',
    surface: '#eff1f5',
    ink: '#4c4f69',
    accent: '#8839ef',
    success: '#40a02b',
    danger: '#d20f39',
    contrast: 45,
  },
  {
    id: 'github-light',
    name: 'GitHub Light',
    type: 'light',
    surface: '#ffffff',
    ink: '#1f2328',
    accent: '#0969da',
    success: '#1a7f37',
    danger: '#cf222e',
    contrast: 42,
  },
  {
    id: 'gruvbox-light',
    name: 'Gruvbox Light',
    type: 'light',
    surface: '#fbf1c7',
    ink: '#3c3836',
    accent: '#af3a03',
    success: '#79740e',
    danger: '#9d0006',
    contrast: 45,
  },
  {
    id: 'kanagawa-lotus',
    name: 'Kanagawa Lotus',
    type: 'light',
    surface: '#f2ecbc',
    ink: '#5c5144',
    accent: '#c47247',
    success: '#6f894e',
    danger: '#c34043',
    contrast: 45,
  },
  {
    id: 'one-light',
    name: 'One Light',
    type: 'light',
    surface: '#fafafa',
    ink: '#383a42',
    accent: '#526fff',
    success: '#50a14f',
    danger: '#e45649',
    contrast: 45,
  },
  {
    id: 'rose-pine-dawn',
    name: 'Rose Pine Dawn',
    type: 'light',
    surface: '#faf4ed',
    ink: '#575279',
    accent: '#d7827e',
    success: '#286983',
    danger: '#b4637a',
    contrast: 42,
  },
]

export function getThemeById(id: string): BuddyTheme | undefined {
  return PRESET_THEMES.find((t) => t.id === id)
}

export function getThemesByType(type: 'dark' | 'light'): BuddyTheme[] {
  return PRESET_THEMES.filter((t) => t.type === type)
}
